development:
  adapter: postgresql
  encoding: unicode
  database: pike
  username: pike
  password: 123456
test:
  adapter: postgresql
  encoding: unicode
  database: pike_test
  username: pike
  password: 123456
